---
- name: Working on different group of hosts
  hosts: dbserver
  tasks:
   - name: Install tree
     apt:
      name: tree
      state: present
  hosts: lb
  tasks:
   - name: Install git
     apt:
      name: git
      state: present



...
