---
- name: Error Handling
  hosts: 192.168.60.24
  tasks:
   - block:
      - name: Install apache1
        apt:
         name: apache1
         state: present
     rescue:
      - name: Install apache2
        apt:
         name: apache2
         state: present
     always:
      - debug:
         msg: "Install successfull"






...
