---
- name: Looping in Ansible
  hosts: dbserver
  tasks:
   - name: Install packages
     apt:
      name: "{{item}}"
      state: present
      update_cache: no
     with_items:
      - tree
      - git
      - maven




...
