---
- name: Installing/uninstalling packages
  hosts: dbserver
  gather_facts: false
  tasks:
   - name: Installing tree
     apt: 
      name: tree
      state: latest
      update_cache: yes
   - name: Uninstall git
     apt:
      name: git
      state: absent
