---
- name: Installing/uinstalling
  hosts: dbserver
  vars:
   - a: apache2
   - b: present
   - c: no  
  tasks:
   - name: installing and uinstalling
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"




...
